language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Qt
  - sudo apt-get update -qq
  - sudo apt-get install -y libqt4-dev qt4-qmake libsmokeqtgui4-3 libsmokeqt4-dev
  # X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # CL
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Stubs
  - git clone https://github.com/Shinmera/dissect ~/quicklisp/dissect
  - git clone https://github.com/Shinmera/simple-tasks ~/quicklisp/simple-tasks
  - git clone https://github.com/Shinmera/trivial-main-thread ~/quicklisp/trivial-main-thread

script:
  - cl -e '(ql:quickload :qtools)'
       -e '(qtools:ensure-qapplication)'
       -e '(format T "~&~%!!! WOAH IT WORKS !!!~&~%")'

notifications:
  email:
    - shinmera@tymoon.eu